publisher_velocity_controller:
  ros__parameters:

    controller_name: "drive_module_steering_angle_controller"
    wait_sec_between_publish: 6

    goal_names: ["vel1", "vel2", "vel3", "vel4"]
    vel1: [1.0, 1.0, 1.0, 1.0]
    vel2: [0.0, 0.0, 0.0, 0.0]
    vel3: [-1.0, -1.0, -1.0, -1.0]
    vel4: [0.0, 0.0, 0.0, 0.0]

    joints:
      - joint_steering_to_wheel_left_front
      - joint_steering_to_wheel_right_front
      - joint_steering_to_wheel_left_rear
      - joint_steering_to_wheel_right_rear

    check_starting_point: false
